const express=require('express'),{DatabaseSync}=require('node:sqlite'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),crypto=require('crypto'),path=require('path');
const db=new DatabaseSync(process.env.DB_PATH||path.join(__dirname,'nova.db'));db.exec('PRAGMA journal_mode=WAL');
const tx=f=>{db.exec('BEGIN');try{const v=f();db.exec('COMMIT');return v}catch(e){db.exec('ROLLBACK');throw e}};
db.exec(`CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT);
CREATE TABLE IF NOT EXISTS menu(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,cat TEXT,price REAL,prep INTEGER,emoji TEXT,img TEXT,avail INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS staff(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,uname TEXT UNIQUE,hash TEXT,role TEXT);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,tbl TEXT,name TEXT,note TEXT,pay TEXT,total REAL,t INTEGER,okey TEXT);
CREATE TABLE IF NOT EXISTS imgs(name TEXT PRIMARY KEY,data BLOB);
CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY AUTOINCREMENT,oid INTEGER,n TEXT,q INTEGER,p REAL,dest TEXT,s TEXT DEFAULT 'pending');`);
const get=(k,d)=>{const r=db.prepare('SELECT v FROM settings WHERE k=?').get(k);return r?r.v:d};
const set=(k,v)=>db.prepare('INSERT INTO settings(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v').run(k,String(v));
if(!get('secret'))set('secret',process.env.JWT_SECRET||crypto.randomBytes(32).toString('hex'));
const SECRET=process.env.JWT_SECRET||get('secret');
if(!get('hotel'))set('hotel',process.env.HOTEL_NAME||'Etetu Abusha Hotel');
if(!db.prepare('SELECT 1 FROM staff').get()){
  const pw=process.env.ADMIN_PASSWORD||crypto.randomBytes(6).toString('base64url');
  db.prepare('INSERT INTO staff(name,uname,hash,role) VALUES(?,?,?,?)').run('Manager','admin',bcrypt.hashSync(pw,10),'admin');
  console.log(`\n  First admin created. Username: admin  Password: ${pw}\n  Sign in at /#/login and change staff accounts in the Staff tab.\n`);
}
if(!db.prepare('SELECT 1 FROM menu').get()){
  const ins=db.prepare('INSERT INTO menu(name,cat,price,prep,emoji) VALUES(?,?,?,?,?)');
  [['Doro Wat','Food',420,25,'🍗'],['Special Kitfo','Food',480,20,'🥩'],['Beef Tibs','Food',390,20,'🍖'],['Fasting Platter','Food',300,15,'🥬'],['Honey Cake','Dessert',120,5,'🍰'],['Ethiopian Coffee','Drink',60,8,'☕'],['Avocado Juice','Drink',110,5,'🥑'],['Mineral Water','Drink',30,1,'💧']].forEach(r=>ins.run(...r));
}
const fs=require('fs');
const UP=process.env.UPLOAD_DIR||path.join(process.env.DB_PATH?path.dirname(process.env.DB_PATH):__dirname,'uploads');fs.mkdirSync(UP,{recursive:true});
const rmImg=u=>{if(u&&u.startsWith('/uploads/'))db.prepare('DELETE FROM imgs WHERE name=?').run(path.basename(u))};
const bk=require('./backup')(db,process.env.DB_PATH||path.join(__dirname,'nova.db'));
const app=express();app.set('trust proxy',1);app.use((q,r,n)=>{if(q.method!=='GET')r.on('finish',()=>{if(r.statusCode<400)bk.schedule()});n()});app.use(express.json({limit:'50kb'}));
const clients=new Set(),ping=()=>clients.forEach(c=>c.write('data: 1\n\n'));
setInterval(()=>clients.forEach(c=>c.write(': ping\n\n')),25000);
const hits={};const limited=(ip,max)=>{const n=Date.now(),a=(hits[ip]=(hits[ip]||[]).filter(t=>n-t<6e5));a.push(n);return a.length>max};
const tokenUser=q=>{try{return jwt.verify((q.headers.authorization||'').slice(7),SECRET)}catch(e){return null}};
const auth=roles=>(q,r,n)=>{const u=tokenUser(q);if(!u)return r.status(401).json({error:'Please sign in'});if(u.role!=='admin'&&!(roles||[]).includes(u.role))return r.status(403).json({error:'Not allowed'});q.u=u;n()};
const admin=auth([]);
const orders=(where,args)=>{const it=db.prepare('SELECT * FROM items WHERE oid=?');return db.prepare(`SELECT * FROM orders ${where} ORDER BY id DESC LIMIT 200`).all(...args).map(o=>({id:o.id,table:o.tbl,name:o.name,note:o.note,pay:o.pay,total:o.total,t:o.t,items:it.all(o.id).map(i=>({n:i.n,q:i.q,p:i.p,dest:i.dest,s:i.s}))}))};
app.post('/api/login',(q,r)=>{if(limited(q.ip,10))return r.status(429).json({error:'Too many attempts. Try again in 10 minutes.'});
  const s=db.prepare('SELECT * FROM staff WHERE uname=?').get(String(q.body.user||''));
  if(!s||!bcrypt.compareSync(String(q.body.pass||''),s.hash))return r.status(401).json({error:'Wrong username or password.'});
  const user={id:s.id,name:s.name,role:s.role};r.json({token:jwt.sign(user,SECRET,{expiresIn:'12h'}),user})});
app.get('/api/state',(q,r)=>{const u=tokenUser(q),isA=u&&u.role==='admin';
  const menu=db.prepare('SELECT id,name,cat,price,prep,emoji,img,avail FROM menu'+(isA?'':' WHERE avail=1')).all().map(m=>({...m,on:!!m.avail}));
  const s={menu,tables:+get('tables','10'),hotel:get('hotel'),orders:[],staff:[]};
  if(u)s.orders=orders('WHERE t>?',[Date.now()-864e5]);
  else if(q.query.order){const[id,key]=String(q.query.order).split('.');s.orders=orders('WHERE id=? AND okey=?',[+id,key||''])}
  if(isA)s.staff=db.prepare('SELECT id,name,uname AS user,role FROM staff').all();
  r.json(s)});
app.post('/api/orders',(q,r)=>{if(limited('o'+q.ip,30))return r.status(429).json({error:'Too many orders. Please ask your waiter.'});
  const b=q.body,list=Array.isArray(b.items)?b.items.slice(0,30):[];const m=db.prepare('SELECT * FROM menu WHERE id=? AND avail=1');
  const rows=list.map(i=>({m:m.get(+i.id),q:Math.min(20,Math.max(1,+i.q|0))})).filter(x=>x.m);
  if(!rows.length)return r.status(400).json({error:'Your cart is empty or items are unavailable.'});
  const key=crypto.randomBytes(6).toString('hex'),total=rows.reduce((s,x)=>s+x.q*x.m.price,0);
  const id=tx(()=>{const o=db.prepare('INSERT INTO orders(tbl,name,note,pay,total,t,okey) VALUES(?,?,?,?,?,?,?)').run(String(b.table||'').slice(0,10),String(b.name||'Guest').slice(0,40)||'Guest',String(b.note||'').slice(0,200),b.pay==='chapa'?'chapa':'later',total,Date.now(),key).lastInsertRowid;
    rows.forEach(x=>db.prepare('INSERT INTO items(oid,n,q,p,dest) VALUES(?,?,?,?,?)').run(o,x.m.name,x.q,x.m.price,x.m.cat==='Drink'?'bar':'kitchen'));return Number(o)});
  ping();r.json({id,key})});
app.post('/api/orders/:id/advance',auth(['kitchen','bar']),(q,r)=>{const d=q.body.dest;if(!['kitchen','bar'].includes(d)||(q.u.role!=='admin'&&q.u.role!==d))return r.status(403).json({error:'Not allowed'});
  const c=['pending','preparing','ready'].find(s=>db.prepare('SELECT 1 FROM items WHERE oid=? AND dest=? AND s=?').get(+q.params.id,d,s));
  if(c)db.prepare('UPDATE items SET s=? WHERE oid=? AND dest=? AND s=?').run({pending:'preparing',preparing:'ready',ready:'served'}[c],+q.params.id,d,c);ping();r.json({ok:1})});
app.post('/api/menu',admin,(q,r)=>{const b=q.body,p=Number(b.price);if(!String(b.name||'').trim()||!(p>=0)||!['Food','Drink','Dessert'].includes(b.cat))return r.status(400).json({error:'Enter a name, category and price.'});
  const img=/^https?:\/\//.test(b.img||'')?b.img:'';const x=db.prepare('INSERT INTO menu(name,cat,price,prep,emoji,img) VALUES(?,?,?,?,?,?)').run(String(b.name).trim().slice(0,60),b.cat,p,Math.max(1,+b.prep||10),String(b.emoji||'').slice(0,4),img);ping();r.json({ok:1,id:Number(x.lastInsertRowid)})});
app.post('/api/menu/:id/image',admin,express.raw({type:'image/*',limit:'3mb'}),(q,r)=>{const b=q.body;
  if(!Buffer.isBuffer(b)||b.length<100||b[0]!==0xFF||b[1]!==0xD8)return r.status(400).json({error:'Please choose a JPG or PNG photo.'});
  const m=db.prepare('SELECT img FROM menu WHERE id=?').get(+q.params.id);if(!m)return r.status(404).json({error:'Item not found.'});
  const f=crypto.randomBytes(8).toString('hex')+'.jpg';db.prepare('INSERT INTO imgs(name,data) VALUES(?,?)').run(f,b);rmImg(m.img);
  db.prepare('UPDATE menu SET img=? WHERE id=?').run('/uploads/'+f,+q.params.id);ping();r.json({img:'/uploads/'+f})});
app.patch('/api/menu/:id',admin,(q,r)=>{const b=q.body;if('price'in b)db.prepare('UPDATE menu SET price=? WHERE id=?').run(Math.max(0,+b.price||0),+q.params.id);
  if('on'in b)db.prepare('UPDATE menu SET avail=? WHERE id=?').run(b.on?1:0,+q.params.id);ping();r.json({ok:1})});
app.delete('/api/menu/:id',admin,(q,r)=>{const m=db.prepare('SELECT img FROM menu WHERE id=?').get(+q.params.id);if(m)rmImg(m.img);db.prepare('DELETE FROM menu WHERE id=?').run(+q.params.id);ping();r.json({ok:1})});
app.post('/api/staff',admin,(q,r)=>{const b=q.body;if(!String(b.name||'').trim()||!String(b.user||'').trim()||String(b.pass||'').length<6||!['kitchen','bar','admin'].includes(b.role))return r.status(400).json({error:'Fill in every field. Password needs 6+ characters.'});
  try{db.prepare('INSERT INTO staff(name,uname,hash,role) VALUES(?,?,?,?)').run(b.name.trim(),b.user.trim(),bcrypt.hashSync(b.pass,10),b.role);r.json({ok:1})}catch(e){r.status(400).json({error:'Username already used.'})}});
app.delete('/api/staff/:id',admin,(q,r)=>{if(+q.params.id===q.u.id)return r.status(400).json({error:'You cannot remove yourself.'});db.prepare('DELETE FROM staff WHERE id=?').run(+q.params.id);r.json({ok:1})});
app.post('/api/tables',admin,(q,r)=>{set('tables',Math.min(100,Math.max(1,+q.body.n||10)));r.json({ok:1})});
app.get('/api/stream',(q,r)=>{r.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache',Connection:'keep-alive'});r.flushHeaders();r.write('retry: 3000\n\n');clients.add(r);q.on('close',()=>clients.delete(r))});
app.get('/uploads/:f',(q,r)=>{const x=db.prepare('SELECT data FROM imgs WHERE name=?').get(path.basename(q.params.f));if(!x)return r.sendStatus(404);r.set({'Content-Type':'image/jpeg','Cache-Control':'public, max-age=604800'}).send(Buffer.from(x.data))});
app.use(express.static(path.join(__dirname,'public')));
app.listen(process.env.PORT||3000,()=>console.log('Nova Digital Menu running on port '+(process.env.PORT||3000)));
